name: Trigger auto deployment for vc-services

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/vc-services-AutoDeployTrigger-72f03101-2033-4563-b2ca-4dd1b68bc046.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.VCSERVICES_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}backend/api
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: cae127fb809bacr.azurecr.io
          registryUsername: ${{ secrets.VCSERVICES_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.VCSERVICES_REGISTRY_PASSWORD }}
          containerAppName: vc-services
          resourceGroup: puzzlequest-value-compass-rg
          imageToBuild: cae127fb809bacr.azurecr.io/vc-services:${{ github.sha }}
          
            

     

